name: Security Vulnerability Scanning

on:
  schedule:
    # Run security scans daily at 2 AM UTC
    - cron: '0 2 * * *'
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      scan_type:
        description: 'Scan type'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - dependencies
          - code
          - secrets

permissions:
  contents: read
  security-events: write
  actions: read
  pull-requests: write

env:
  NODE_VERSION: '20.x'

jobs:
  dependency-scan:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Run npm audit
        run: |
          npm audit --json > npm-audit-report.json || true
          npm audit --production --json > npm-audit-prod-report.json || true

      - name: Run npm audit (Human Readable)
        run: |
          npm audit --audit-level=moderate || true

      - name: Check for Critical Vulnerabilities
        id: critical-check
        run: |
          if grep -q '"severity":"critical"' npm-audit-report.json; then
            echo "Critical vulnerabilities found!"
            echo "critical_found=true" >> $GITHUB_OUTPUT
            cat npm-audit-report.json | jq '.vulnerabilities | to_entries[] | select(.value.severity == "critical") | {package: .key, severity: .value.severity, url: .value.url}'
            exit 1
          else
            echo "critical_found=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload Audit Reports
        uses: actions/upload-artifact@v4
        with:
          name: dependency-audit-reports
          path: |
            npm-audit-report.json
            npm-audit-prod-report.json
          retention-days: 30

      - name: Comment PR with Vulnerabilities
        if: github.event_name == 'pull_request' && steps.critical-check.outputs.critical_found == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = JSON.parse(fs.readFileSync('npm-audit-report.json', 'utf8'));
            const criticalVulns = Object.entries(report.vulnerabilities || {})
              .filter(([_, v]) => v.severity === 'critical')
              .map(([name, v]) => `**${name}**: ${v.title}\n- Via: ${v.via.map(v => v.title).join(', ')}`)
              .join('\n\n');

            if (criticalVulns) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `## âš ï¸ Critical Vulnerabilities Found\\n\\n${criticalVulns}\\n\\nPlease address these vulnerabilities before merging.`
              });
            }

  code-security-scan:
    name: Code Security Scan (CodeQL)
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ['javascript', 'typescript']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
          queries: security-extended,security-and-quality

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"

  secrets-scan:
    name: Secrets Detection Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trivy Secret Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-secrets-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Secrets Scan Results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-secrets-results.sarif'

      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        with:
          report-format: sarif
          output: gitleaks-results.sarif

      - name: Upload Gitleaks Results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'gitleaks-results.sarif'

      - name: Comment Secrets Found
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '## ðŸ”’ Secrets Detected\\n\\nThe security scan detected potential secrets in this pull request. Please review and remove any sensitive data before merging.'
            });

  container-scan:
    name: Container Image Security Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'schedule'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Test Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.opencode/workflows/docker/Dockerfile
          push: false
          tags: test-image:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: test-image:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-container-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          scan-type: 'image'

      - name: Upload Container Scan Results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-container-results.sarif'

      - name: Generate Container Security Report
        run: |
          trivy image --format json --output trivy-container-report.json test-image:${{ github.sha }}

      - name: Upload Container Report
        uses: actions/upload-artifact@v4
        with:
          name: container-security-report
          path: trivy-container-report.json
          retention-days: 30

  dependency-check:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'frontend-design-agent-system'
          path: '.'
          format: 'ALL'
          out: 'reports'
          scanDependencies: true
        continue-on-error: true

      - name: Upload OWASP Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: owasp-dependency-check-reports
          path: reports/
          retention-days: 30

      - name: Check OWASP Results
        run: |
          if [ -f "reports/dependency-check-report.json" ]; then
            CRITICAL_COUNT=$(cat reports/dependency-check-report.json | jq '.dependencies[] | select(.vulnerabilities != null) | .vulnerabilities[] | select(.severity == "CRITICAL")' | wc -l)
            if [ "$CRITICAL_COUNT" -gt 0 ]; then
              echo "Found $CRITICAL_COUNT critical vulnerabilities"
              exit 1
            fi
          fi

  sbom-generation:
    name: Generate SBOM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Generate CycloneDX SBOM
        uses: CycloneDX/gh-action-generate-sbom@v2
        with:
          path: ./
          output-file: sbom.cdx.json
          output-format: json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ github.sha }}
          path: sbom.cdx.json
          retention-days: 365

      - name: Generate SPDX SBOM
        run: |
          npm install -g @cyclonedx/bom
          cyclonedx-bom -o sbom.spdx.json --format json
        continue-on-error: true

      - name: Upload SPDX SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-spdx-${{ github.sha }}
          path: sbom.spdx.json
          retention-days: 365

  license-compliance:
    name: License Compliance Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Generate License Report
        run: |
          npm install -g license-checker
          license-checker --json --production > license-report.json || true
          license-checker --json > license-report-all.json || true

      - name: Check for Problematic Licenses
        id: license-check
        run: |
          PROBLEMATIC_LICENSES=("GPL" "AGPL" "SSPL")
          FOUND_ISSUES=false

          for license in "${PROBLEMATIC_LICENSES[@]}"; do
            if grep -i "$license" license-report.json; then
              echo "Found package with $license license"
              FOUND_ISSUES=true
            fi
          done

          if [ "$FOUND_ISSUES" = true ]; then
            echo "issues_found=true" >> $GITHUB_OUTPUT
          else
            echo "issues_found=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload License Report
        uses: actions/upload-artifact@v4
        with:
          name: license-compliance-report
          path: |
            license-report.json
            license-report-all.json
          retention-days: 30

      - name: Comment License Issues
        if: github.event_name == 'pull_request' && steps.license-check.outputs.issues_found == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = JSON.parse(fs.readFileSync('license-report.json', 'utf8'));

            const problematic = Object.entries(report)
              .filter(([_, v]) => /GPL|AGPL|SSPL/i.test(v.licenses))
              .map(([name, v]) => `**${name}**: ${v.licenses}`)
              .join('\n\n');

            if (problematic) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `## âš–ï¸ License Compliance Issues\\n\\nThe following packages have potentially problematic licenses:\\n\\n${problematic}\\n\\nPlease review before merging.`
              });
            }

  security-summary:
    name: Security Scan Summary
    runs-on: ubuntu-latest
    needs: [dependency-scan, code-security-scan, secrets-scan, container-scan, dependency-check, license-compliance]
    if: always()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download All Reports
        uses: actions/download-artifact@v4
        with:
          path: security-reports

      - name: Generate Security Summary
        run: |
          cat > security-summary.md << EOF
          # Security Scan Summary

          ## Scan Results

          | Scan Type | Status | Details |
          |-----------|--------|---------|
          | Dependency Scan | ${{ needs.dependency-scan.result }} | Critical vulns: ${{ needs.dependency-scan.outputs.critical_found == 'true' ? 'Yes' : 'No' }} |
          | Code Security Scan | ${{ needs.code-security-scan.result }} | CodeQL analysis |
          | Secrets Scan | ${{ needs.secrets-scan.result }} | Gitleaks/Trivy |
          | Container Scan | ${{ needs.container-scan.result }} | Image: ${{ github.sha }} |
          | OWASP Dependency Check | ${{ needs.dependency-check.result }} | CVE database |
          | License Compliance | ${{ needs.license-compliance.result }} | ${{ needs.license-compliance.outputs.issues_found == 'true' ? 'Issues found' : 'Compliant' }} |

          ## Recommendations

          - Review any critical or high severity findings
          - Update dependencies with known vulnerabilities
          - Remove any detected secrets
          - Ensure license compliance
          - Schedule regular security scans

          ## Reports Available

          - Dependency audit reports
          - CodeQL results
          - Secrets scan results
          - Container security reports
          - OWASP dependency check
          - License compliance reports

          Scan completed at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
          EOF

      - name: Upload Security Summary
        uses: actions/upload-artifact@v4
        with:
          name: security-summary-${{ github.sha }}
          path: security-summary.md
          retention-days: 90

      - name: Create Security Issue (if problems found)
        if: github.event_name == 'schedule' && failure()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const summary = fs.readFileSync('security-summary.md', 'utf8');

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Security Scan Failed - ${new Date().toISOString().split('T')[0]}`,
              body: summary,
              labels: ['security', 'automated']
            });

      - name: Comment PR with Security Results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const summary = fs.readFileSync('security-summary.md', 'utf8');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: summary
            });
